# Generated by Django 4.2 on 2024-04-14 12:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100, verbose_name='Населенный пункт')),
                ('region', models.CharField(max_length=100, verbose_name='Субъект федерации')),
                ('federal_district', models.CharField(choices=[('ЦФО', 'Центральный федеральный округ'), ('СЗФО', 'Северо-Западный федеральный округ'), ('ЮФО', 'Южный федеральный округ'), ('ПФО', 'Приволжский федеральный округ'), ('УФО', 'Уральский федеральный округ'), ('СФО', 'Сибирский федеральный округ'), ('ДВФО', 'Дальневосточный федеральный округ')], max_length=100, verbose_name='Федеральный округ')),
            ],
            options={
                'verbose_name': 'Населенный пункт',
                'verbose_name_plural': 'Населенные пункты',
                'ordering': ['city'],
                'unique_together': {('city', 'region', 'federal_district')},
            },
        ),
        migrations.CreateModel(
            name='RailwayStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('station_name', models.CharField(max_length=100, verbose_name='Станция')),
                ('station_id', models.PositiveIntegerField()),
                ('station_branch', models.CharField(choices=[('ОЖД', 'Октябрьская ж/д'), ('КаЖД', 'Калининградская ж/д'), ('МЖД', 'Московская ж/д'), ('ГЖД', 'Горьковская ж/д'), ('СеЖД', 'Северная ж/д'), ('СКЖД', 'Северо-Кавказская ж/д'), ('ЮВЖД', 'Юго-Восточная ж/д'), ('ПЖД', 'Приволжская ж/д'), ('КуЖД', 'Куйбышевская ж/д'), ('СвЖД', 'Свердловская ж/д'), ('ЮУЖД', 'Южно-Уральская ж/д'), ('ЗСЖД', 'Западно-Сибирская ж/д'), ('КЖД', 'Красноярская ж/д'), ('ВСЖД', 'Восточно-Сибирская ж/д'), ('ЗЖД', 'Забайкальская ж/д'), ('ДВЖД', 'Дальневосточная ж/д')], max_length=255)),
            ],
            options={
                'verbose_name': 'Ж/д станция',
                'verbose_name_plural': 'Ж/д станции',
                'ordering': ['station_name'],
                'unique_together': {('station_name', 'station_id')},
            },
        ),
        migrations.CreateModel(
            name='TripRailway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_tonn_rw', models.PositiveIntegerField()),
                ('departure_station_name', models.ForeignKey(db_column='departure_station_name', on_delete=django.db.models.deletion.PROTECT, related_name='departure_station_name', to='logistics.railwaystation')),
                ('destination_station_name', models.ForeignKey(db_column='destination_station_name', on_delete=django.db.models.deletion.PROTECT, related_name='destination_station_name', to='logistics.railwaystation')),
            ],
            options={
                'verbose_name': 'Перевозки ж/д',
                'verbose_name_plural': 'Перевозки ж/д',
                'ordering': ['departure_station_name', 'destination_station_name'],
                'unique_together': {('departure_station_name', 'destination_station_name')},
            },
        ),
        migrations.CreateModel(
            name='TripAuto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_per_tonn_auto', models.PositiveIntegerField(verbose_name='Цена за рейс, руб./тн')),
                ('departure_city', models.ForeignKey(db_column='departure_city', on_delete=django.db.models.deletion.PROTECT, related_name='departure_city', to='logistics.city')),
                ('destination_city', models.ForeignKey(db_column='destination_city', on_delete=django.db.models.deletion.PROTECT, related_name='destination_city', to='logistics.city')),
            ],
            options={
                'verbose_name': 'Перевозки авто',
                'verbose_name_plural': 'Перевозки авто',
                'ordering': ['departure_city', 'destination_city'],
                'unique_together': {('departure_city', 'destination_city')},
            },
        ),
    ]
