# Generated by Django 5.0.6 on 2024-06-05 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='city',
            unique_together={('city', 'region')},
        ),
        migrations.AlterField(
            model_name='city',
            name='region',
            field=models.CharField(max_length=100, verbose_name='Регион'),
        ),
        migrations.RemoveField(
            model_name='city',
            name='federal_district',
        ),
    ]
