# Generated by Django 4.2 on 2024-02-16 08:28

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(
            name="Factory",
        ),
    ]
