# Generated by Django 4.2 on 2024-03-07 17:48

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_customuser_department_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="customuser",
            options={
                "verbose_name": "Пользователь",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterModelOptions(
            name="department",
            options={
                "verbose_name": "Департамент",
                "verbose_name_plural": "Департаменты",
            },
        ),
        migrations.AlterModelOptions(
            name="position",
            options={"verbose_name": "Позиция", "verbose_name_plural": "Позиции"},
        ),
        migrations.AlterField(
            model_name="customuser",
            name="department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.department",
                verbose_name="Департамент",
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(max_length=50, unique=True, verbose_name="E-mail"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="full_name",
            field=models.CharField(max_length=75, verbose_name="ФИО"),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number_personal",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Личный телефон"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="phone_number_work",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Рабочий телефон"
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="users.position",
                verbose_name="Позиция",
            ),
        ),
    ]
