# Generated by Django 4.2 on 2024-01-17 06:31

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_delete_logisticsauto_delete_logisticsrailwaystations"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "ordering": ["username"],
                "verbose_name": "Пользователи",
                "verbose_name_plural": "Пользователи",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.CharField(max_length=50, verbose_name="Отдел"),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(max_length=50, verbose_name="Имя"),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(max_length=50, verbose_name="Фамилия"),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number_personal",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Рабочий телефон"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone_number_work",
            field=phonenumber_field.modelfields.PhoneNumberField(
                max_length=128, region=None, verbose_name="Личный телефон"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="position",
            field=models.CharField(max_length=50, verbose_name="Должность"),
        ),
    ]
