version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Melnichanka123
      POSTGRES_DB: meln_db
    ports:
      - "5432:5432"
    networks:
      - melnichanka
  web:
    build: .
    command: sh entrypoint.sh
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    networks:
      - melnichanka
  nginx:
    image: nginx:1.24-alpine
    ports:
      - "80:80"
    depends_on:
      - web
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./static:/app/static
    networks:
      - melnichanka
networks:
  melnichanka:
