version: '3.8'
services:
  db:
    image: postgres:14
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: Melnichanka123
      POSTGRES_DB: meln_db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - melnichanka

  nginx:
    image: nginx:1.24-alpine
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    ports:
      - "80:80"
    networks:
      - melnichanka

  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    command: sh entrypoint.sh
    networks:
      - melnichanka
    volumes:
      - static_volume:/static
    depends_on:
    - db

networks:
  melnichanka:

volumes:
  static_volume:
  postgres_data:
