services:
  db:
    image: postgres:16.3-alpine
    env_file:
      - .env
    environment:
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
      POSTGRES_DB: ${DATABASE_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5432:5432"
    networks:
      - melnichanka
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 10s
      timeout: 1s
      retries: 5

  nginx:
    image: nginx:stable-alpine3.17-slim
    restart: on-failure
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
      - /home/ubuntu/nginx-selfsigned.crt:/etc/nginx/ssl/nginx-selfsigned.crt
      - /home/ubuntu/nginx-selfsigned.key:/etc/nginx/ssl/nginx-selfsigned.key
      - static_volume:/app/static/
    ports:
      - "80:80"
      - "443:443"
    networks:
      - melnichanka

  web:
    build: .
    env_file: .env
    ports:
      - "8000:8000"
    command: sh entrypoint.sh
    networks:
      - melnichanka
    volumes:
      - static_volume:/app/static/
    depends_on:
      db:
        condition: service_healthy

  redis:
    image: redis:7.2.5-alpine
    hostname: redis
    ports:
      - "6379:6379"
    networks:
      - melnichanka

networks:
  melnichanka:

volumes:
  static_volume:
  postgres_data:
