# Generated by Django 4.2 on 2024-04-18 08:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DirectorPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('director_position', models.CharField(max_length=40)),
            ],
            options={
                'verbose_name': 'Должность директора',
                'verbose_name_plural': 'Должность директора',
            },
        ),
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100, verbose_name='Наименование организации')),
                ('contract_number', models.CharField(max_length=50, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата заключения договора')),
                ('director_name', models.CharField(max_length=100, verbose_name='ФИО директора')),
                ('receiver_name', models.CharField(blank=True, max_length=100, verbose_name='Имя получателя')),
                ('receiver_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер получателя')),
                ('receiver_okpo', models.PositiveIntegerField(blank=True, null=True, verbose_name='ОКПО')),
                ('receiver_adress', models.CharField(blank=True, max_length=200, verbose_name='Адрес получателя')),
                ('special_marks', models.CharField(blank=True, max_length=200, verbose_name='Особые отметки')),
                ('last_application_number', models.CharField(blank=True, max_length=50, verbose_name='Номер приложения')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='logistics.city', verbose_name='Город доставки')),
                ('director_position', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='clients.directorposition', verbose_name='Должность директора')),
                ('railway_station', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='logistics.railwaystation', verbose_name='ЖД станция')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'unique_together': {('client_name', 'contract_number')},
            },
        ),
    ]
