# Generated by Django 4.2 on 2024-04-18 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Director_position',
            new_name='DirectorPosition',
        ),
    ]
