# Generated by Django 4.2 on 2024-01-18 14:15

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Clients",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "client_name",
                    models.CharField(
                        blank=True, max_length=100, verbose_name="Название предприятия"
                    ),
                ),
                (
                    "contract_number",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        unique=True,
                        verbose_name="Номер договора",
                    ),
                ),
                (
                    "contract_date",
                    models.DateField(verbose_name="Дата заключения договора"),
                ),
                (
                    "director_position",
                    models.CharField(max_length=100, verbose_name=" "),
                ),
                (
                    "director_name",
                    models.CharField(max_length=100, verbose_name="Имя директора"),
                ),
                (
                    "special_marks",
                    models.CharField(
                        max_length=200, verbose_name="Специальнные отметки"
                    ),
                ),
                (
                    "destination_station_name",
                    models.CharField(max_length=100, verbose_name="Имя ЖД станции"),
                ),
                (
                    "destination_station_id",
                    models.PositiveIntegerField(verbose_name="Номер ЖД станции"),
                ),
                (
                    "receiver_name",
                    models.CharField(max_length=100, verbose_name="Имя получателя"),
                ),
                (
                    "receiver_id",
                    models.PositiveIntegerField(verbose_name="Номер получателя"),
                ),
                ("receiver_okpo", models.PositiveIntegerField(verbose_name="ОКПО")),
                (
                    "receiver_adress",
                    models.CharField(max_length=200, verbose_name="Адрес получателя"),
                ),
                (
                    "last_application_number",
                    models.CharField(max_length=50, verbose_name="Номер приложения"),
                ),
            ],
            options={
                "verbose_name": "Клиенты",
                "verbose_name_plural": "Клиенты",
            },
        ),
    ]
