# Generated by Django 4.2 on 2024-02-22 18:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Clients',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(blank=True, max_length=100, verbose_name='Наименование организации')),
                ('contract_number', models.CharField(blank=True, max_length=50, unique=True, verbose_name='Номер договора')),
                ('contract_date', models.DateField(verbose_name='Дата заключения договора')),
                ('director_position', models.CharField(max_length=100, verbose_name='Должность директора')),
                ('director_name', models.CharField(max_length=100, verbose_name='ФИО директора')),
                ('receiver_name', models.CharField(max_length=100, verbose_name='Имя получателя')),
                ('receiver_id', models.PositiveIntegerField(verbose_name='Номер получателя')),
                ('receiver_okpo', models.PositiveIntegerField(verbose_name='ОКПО')),
                ('receiver_adress', models.CharField(max_length=200, verbose_name='Адрес получателя')),
                ('special_marks', models.CharField(max_length=200, verbose_name='Особые отметки')),
                ('last_application_number', models.CharField(max_length=50, verbose_name='Номер приложения')),
                ('destination_city', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='logistics.railwaystations', verbose_name='ЖД станция')),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
            },
        ),
    ]
