# Generated by Django 4.2 on 2024-02-14 09:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0001_initial"),
        ("clients", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="clients",
            name="destination_station_id",
        ),
        migrations.RemoveField(
            model_name="clients",
            name="destination_station_name",
        ),
        migrations.AddField(
            model_name="clients",
            name="destination_city",
            field=models.ForeignKey(
                default=3,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="clients",
                to="logistics.railwaystations",
                verbose_name="ЖД станция",
            ),
            preserve_default=False,
        ),
    ]
