# Generated by Django 4.2 on 2024-03-03 20:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_clients_railway_station_alter_clients_client_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='receiver_id',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Номер получателя'),
        ),
        migrations.AlterField(
            model_name='clients',
            name='receiver_okpo',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='ОКПО'),
        ),
    ]
