# Generated by Django 4.2 on 2024-03-03 20:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0004_rename_logisticscity_city_and_more'),
        ('clients', '0003_alter_clients_receiver_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clients',
            name='railway_station',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='clients', to='logistics.railwaystations', verbose_name='ЖД станция'),
        ),
    ]
