# Generated by Django 4.2 on 2024-03-07 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0004_rename_logisticscity_city_and_more"),
        ("clients", "0004_alter_clients_railway_station"),
    ]

    operations = [
        migrations.AlterField(
            model_name="clients",
            name="destination_city",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to="logistics.city",
                verbose_name="Город доставки",
            ),
        ),
    ]
