# Generated by Django 4.2 on 2024-01-14 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='logisticsauto',
            unique_together={('departure_city', 'destination_city')},
        ),
        migrations.AlterUniqueTogether(
            name='logisticsrailwaystations',
            unique_together={('departure_station_name', 'destination_station_name')},
        ),
    ]
