# Generated by Django 4.2 on 2024-02-22 06:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('logistics', '0002_delete_factory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logisticsauto',
            name='departure_city',
            field=models.ForeignKey(db_column='departure_city', on_delete=django.db.models.deletion.PROTECT, related_name='departure_city', to='logistics.logisticscity'),
        ),
        migrations.AlterField(
            model_name='logisticsauto',
            name='destination_city',
            field=models.ForeignKey(db_column='destination_city', on_delete=django.db.models.deletion.PROTECT, related_name='destination_city', to='logistics.logisticscity'),
        ),
        migrations.AlterField(
            model_name='logisticsrailwaystations',
            name='departure_station_name',
            field=models.ForeignKey(db_column='departure_station_name', on_delete=django.db.models.deletion.PROTECT, related_name='departure_station_name', to='logistics.railwaystations'),
        ),
        migrations.AlterField(
            model_name='logisticsrailwaystations',
            name='destination_station_name',
            field=models.ForeignKey(db_column='destination_station_name', on_delete=django.db.models.deletion.PROTECT, related_name='destination_station_name', to='logistics.railwaystations'),
        ),
        migrations.AlterUniqueTogether(
            name='logisticscity',
            unique_together={('city', 'region', 'federal_district')},
        ),
        migrations.AlterUniqueTogether(
            name='railwaystations',
            unique_together={('station_name', 'station_id')},
        ),
    ]
