# Generated by Django 4.2 on 2024-01-17 06:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("logistics", "0003_alter_logisticsauto_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="logisticsauto",
            options={
                "ordering": ["departure_city", "destination_city"],
                "verbose_name": "Логистика авто",
                "verbose_name_plural": "Логистика авто",
            },
        ),
        migrations.AlterModelOptions(
            name="logisticsrailwaystations",
            options={
                "ordering": ["departure_station_name", "destination_station_name"],
                "verbose_name": "Логистика ж/д",
                "verbose_name_plural": "Логистика ж/д",
            },
        ),
        migrations.AlterField(
            model_name="logisticsauto",
            name="cost_per_tonn_auto",
            field=models.PositiveIntegerField(verbose_name="Цена за рейс, руб./тн"),
        ),
        migrations.AlterField(
            model_name="logisticsauto",
            name="departure_city",
            field=models.CharField(
                choices=[
                    ("Курск", "АО Курский Комбинат Хлебопродуктов"),
                    ("Оскол", "АО Комбинат Хлебопродуктов Старооскольский"),
                    ("Волгоград", "АО Городищенский Комбинат Хлебопродуктов"),
                ],
                max_length=9,
                verbose_name="Комбинат грузоотправитель",
            ),
        ),
        migrations.AlterField(
            model_name="logisticsauto",
            name="destination_city",
            field=models.CharField(max_length=50, verbose_name="Город назначения"),
        ),
    ]
