# Generated by Django 4.2 on 2024-02-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Goods",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flour_name",
                    models.CharField(
                        choices=[
                            (
                                "Мука пшеничная хлебопекарная сорт экстра",
                                "Мука пшеничная хлебопекарная сорт экстра",
                            ),
                            (
                                "Мука пшеничная хлебопекарная высший сорт",
                                "Мука пшеничная хлебопекарная высший сорт",
                            ),
                            (
                                "Мука пшеничная хлебопекарная первый сорт",
                                "Мука пшеничная хлебопекарная первый сорт",
                            ),
                            (
                                "Мука пшеничная общего назначения тип М55-23",
                                "Мука пшеничная общего назначения тип М55-23",
                            ),
                            (
                                "Мука пшеничная общего назначения тип М75-23",
                                "Мука пшеничная общего назначения тип М75-23",
                            ),
                            ("Мука ржаная обдирная", "Мука ржаная обдирная"),
                            ("Мука ржаная сеяная", "Мука ржаная сеяная"),
                            ("Крупа манная марка М", "Крупа манная марка М"),
                            ("Мука цельнозерновая", "Мука цельнозерновая"),
                            (
                                "Мука пшеничная хлебопекарная второй сорт",
                                "Мука пшеничная хлебопекарная второй сорт",
                            ),
                        ],
                        max_length=255,
                        verbose_name="Сорт муки",
                    ),
                ),
                (
                    "brand",
                    models.CharField(
                        choices=[
                            ("Французская штучка", "Французская штучка"),
                            (
                                "Французская штучка для хлебопечки",
                                "Французская штучка для хлебопечки",
                            ),
                            ("Бело-Нежная", "Бело-Нежная"),
                            ("Славна", "Славна"),
                            ("Старооскольская", "Старооскольская"),
                            ("Курская", "Курская"),
                            ("Акция", "Акция"),
                        ],
                        max_length=100,
                        verbose_name="Брэнд",
                    ),
                ),
                (
                    "package",
                    models.IntegerField(
                        choices=[
                            (0, 0),
                            (1, 1),
                            (2, 2),
                            (5, 5),
                            (10, 10),
                            (25, 25),
                            (40, 40),
                            (45, 45),
                            (50, 50),
                        ],
                        verbose_name="Тара",
                    ),
                ),
                (
                    "unit_weight",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Вес единицы"
                    ),
                ),
                (
                    "group_quantity",
                    models.PositiveIntegerField(
                        verbose_name="Количество штук в упаковке"
                    ),
                ),
                (
                    "factory",
                    models.CharField(
                        choices=[
                            ("Курск", "Курск"),
                            ("Оскол", "Оскол"),
                            ("Волгоград", "Волгоград"),
                        ],
                        verbose_name="Изготовитель",
                    ),
                ),
                (
                    "pallet_weight",
                    models.PositiveBigIntegerField(verbose_name="Вес на паллете"),
                ),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "Упаковка",
                "verbose_name_plural": "Упаковка",
                "ordering": ["flour_name", "brand"],
                "unique_together": {("flour_name", "brand", "package", "price")},
            },
        ),
    ]
