# Generated by Django 4.2 on 2024-02-16 08:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Package',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flour_name', models.CharField(choices=[('Мука пшеничная хлебопекарная сорт экстра', 'Мука пшеничная хлебопекарная сорт экстра'), ('Мука пшеничная хлебопекарная высший сорт', 'Мука пшеничная хлебопекарная высший сорт'), ('Мука пшеничная хлебопекарная первый сорт', 'Мука пшеничная хлебопекарная первый сорт'), ('Мука пшеничная общего назначения тип М55-23', 'Мука пшеничная общего назначения тип М55-23'), ('Мука пшеничная общего назначения тип М75-23', 'Мука пшеничная общего назначения тип М75-23'), ('Мука ржаная обдирная', 'Мука ржаная обдирная'), ('Мука ржаная сеяная', 'Мука ржаная сеяная'), ('Крупа манная марка М', 'Крупа манная марка М'), ('Мука цельнозерновая', 'Мука цельнозерновая'), ('Мука пшеничная хлебопекарная второй сорт', 'Мука пшеничная хлебопекарная второй сорт')], max_length=255, verbose_name='Сорт муки')),
                ('unit_weight', models.PositiveIntegerField(verbose_name='Вес единицы')),
                ('group_quantity', models.PositiveIntegerField(verbose_name='Количество штук в упаковке')),
                ('factory', models.CharField(choices=[('Курск', 'ККХП'), ('Оскол', 'КХПС'), ('Волгоград', 'ГКХП')], verbose_name='Изготовитель')),
                ('pallet_weight', models.PositiveIntegerField(verbose_name='Вес на паллете')),
            ],
            options={
                'verbose_name': 'Упаковка',
                'verbose_name_plural': 'Упаковка',
            },
        ),
        migrations.AlterModelOptions(
            name='goods',
            options={'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.RemoveField(
            model_name='goods',
            name='flour_name',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='group_quantity',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='pallet_weight',
        ),
        migrations.RemoveField(
            model_name='goods',
            name='unit_weight',
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(choices=[('Французская штучка', 'Французская штучка'), ('Французская штучка для хлебопечки', 'Французская штучка для хлебопечки'), ('Бело-Нежная', 'Бело-Нежная'), ('Славна', 'Славна'), ('Старооскольская', 'Старооскольская'), ('Курская', 'Курская'), ('Акция', 'Акция')], max_length=100, verbose_name='Брэнд'),
        ),
        migrations.AddField(
            model_name='goods',
            name='flour',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='flour', to='goods.package'),
            preserve_default=False,
        ),
    ]
