# Generated by Django 4.2 on 2024-02-20 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0002_remove_goods_unit_weight_alter_goods_pallet_weight_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='goods',
            name='brand',
            field=models.CharField(blank=True, choices=[('Французская штучка', 'Французская штучка'), ('Французская штучка для хлебопечки', 'Французская штучка для хлебопечки'), ('Бело-Нежная', 'Бело-Нежная'), ('Славна', 'Славна'), ('Старооскольская', 'Старооскольская'), ('Курская', 'Курская'), ('Акция', 'Акция')], max_length=100, verbose_name='Брэнд'),
        ),
        migrations.AlterField(
            model_name='goods',
            name='group_quantity',
            field=models.PositiveIntegerField(choices=[(0, 0), (1, 1), (6, 6), (10, 10), (12, 12)], verbose_name='Количество штук в упаковке'),
        ),
        migrations.AlterUniqueTogether(
            name='goods',
            unique_together={('flour_name', 'brand', 'package')},
        ),
    ]
