# Generated by Django 4.2 on 2024-02-27 09:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0005_alter_goods_options"),
    ]

    operations = [
        migrations.CreateModel(
            name="Brand",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "brand",
                    models.CharField(blank=True, max_length=100, verbose_name="Брэнд"),
                ),
            ],
            options={
                "verbose_name": "Брэнд",
                "verbose_name_plural": "Брэнды",
                "ordering": ["brand"],
            },
        ),
        migrations.CreateModel(
            name="Factory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(
                        max_length=100, verbose_name="Полное название предприятия"
                    ),
                ),
                (
                    "short_name",
                    models.CharField(
                        max_length=100, verbose_name="Краткое название предприятия"
                    ),
                ),
                (
                    "full_address",
                    models.CharField(max_length=100, verbose_name="Адрес предприятия"),
                ),
                (
                    "departure_city",
                    models.CharField(max_length=100, verbose_name="Город отправления"),
                ),
                (
                    "departure_station_branch",
                    models.CharField(
                        choices=[
                            ("ОЖД", "Октябрьская ж/д"),
                            ("КаЖД", "Калининградская ж/д"),
                            ("МЖД", "Московская ж/д"),
                            ("ГЖД", "Горьковская ж/д"),
                            ("СеЖД", "Северная ж/д"),
                            ("СКЖД", "Северо-Кавказская ж/д"),
                            ("ЮВЖД", "Юго-Восточная ж/д"),
                            ("ПЖД", "Приволжская ж/д"),
                            ("КуЖД", "Куйбышевская ж/д"),
                            ("СвЖД", "Свердловская ж/д"),
                            ("ЮУЖД", "Южно-Уральская ж/д"),
                            ("ЗСЖД", "Западно-Сибирская ж/д"),
                            ("КЖД", "Красноярская ж/д"),
                            ("ВСЖД", "Восточно-Сибирская ж/д"),
                            ("ЗЖД", "Забайкальская ж/д"),
                            ("ДВЖД", "Дальневосточная ж/д"),
                        ],
                        max_length=100,
                        verbose_name="Ж/Д станция",
                    ),
                ),
                (
                    "departure_station_id",
                    models.PositiveIntegerField(verbose_name="Код ж/д стации"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Flour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("flour_name", models.CharField(max_length=255)),
            ],
            options={
                "verbose_name": "Мука",
                "verbose_name_plural": "Мука",
                "ordering": ["flour_name"],
            },
        ),
        migrations.CreateModel(
            name="Package",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("package", models.IntegerField(verbose_name="Тара")),
                (
                    "pallet_weight",
                    models.PositiveIntegerField(verbose_name="Вес на паллете"),
                ),
                (
                    "factory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, to="goods.factory"
                    ),
                ),
            ],
            options={
                "verbose_name": "Упаковка",
                "verbose_name_plural": "Упаковка",
                "ordering": ["package", "factory"],
                "unique_together": {("package", "factory", "pallet_weight")},
            },
        ),
        migrations.AlterUniqueTogether(
            name="goods",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="goods",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_brand",
                to="goods.brand",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="flour_name",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_flour",
                to="goods.flour",
            ),
        ),
        migrations.AlterField(
            model_name="goods",
            name="package",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_package",
                to="goods.package",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="goods",
            unique_together={("flour_name", "brand", "package", "price")},
        ),
        migrations.RemoveField(
            model_name="goods",
            name="factory",
        ),
        migrations.RemoveField(
            model_name="goods",
            name="group_quantity",
        ),
        migrations.RemoveField(
            model_name="goods",
            name="pallet_weight",
        ),
    ]
