# Generated by Django 4.2 on 2024-02-27 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goods', '0006_brand_factory_flour_package_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='factory',
            options={'ordering': ['-full_name'], 'verbose_name': 'Предприятие', 'verbose_name_plural': 'Предприятия'},
        ),
        migrations.AddField(
            model_name='factory',
            name='departure_station_name',
            field=models.CharField(default='Станция', max_length=100, verbose_name='Ж/Д станция'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='factory',
            name='departure_station_branch',
            field=models.CharField(choices=[('ОЖД', 'Октябрьская ж/д'), ('КаЖД', 'Калининградская ж/д'), ('МЖД', 'Московская ж/д'), ('ГЖД', 'Горьковская ж/д'), ('СеЖД', 'Северная ж/д'), ('СКЖД', 'Северо-Кавказская ж/д'), ('ЮВЖД', 'Юго-Восточная ж/д'), ('ПЖД', 'Приволжская ж/д'), ('КуЖД', 'Куйбышевская ж/д'), ('СвЖД', 'Свердловская ж/д'), ('ЮУЖД', 'Южно-Уральская ж/д'), ('ЗСЖД', 'Западно-Сибирская ж/д'), ('КЖД', 'Красноярская ж/д'), ('ВСЖД', 'Восточно-Сибирская ж/д'), ('ЗЖД', 'Забайкальская ж/д'), ('ДВЖД', 'Дальневосточная ж/д')], max_length=100, verbose_name='Ветка ж/д стации'),
        ),
        migrations.AlterUniqueTogether(
            name='factory',
            unique_together={('full_name', 'short_name', 'full_address')},
        ),
    ]
