# Generated by Django 4.2 on 2024-02-27 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0007_alter_factory_options_factory_departure_station_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="brand",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_brand",
                to="goods.brand",
            ),
        ),
    ]
