# Generated by Django 4.2 on 2024-06-07 17:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('goods', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Factory',
        ),
    ]
