# Generated by Django 4.2 on 2024-02-27 10:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("goods", "0008_alter_goods_brand"),
    ]

    operations = [
        migrations.AlterField(
            model_name="goods",
            name="brand",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="goods_brand",
                to="goods.brand",
            ),
        ),
    ]
