# Generated by Django 4.2 on 2023-12-26 12:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voiceconvert", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="password",
            field=models.CharField(max_length=150),
        ),
    ]
