# Generated by Django 4.2 on 2024-01-06 17:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voiceconvert", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="department",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="position",
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
    ]
