# Generated by Django 4.2 on 2024-01-09 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("voiceconvert", "0002_user_department_user_position"),
    ]

    operations = [
        migrations.CreateModel(
            name="Client",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("company_name", models.CharField(max_length=100)),
                ("contract_number", models.CharField(max_length=50, unique=True)),
                ("contract_date", models.DateField()),
                ("director_position", models.CharField(max_length=100)),
                ("director_name", models.CharField(max_length=100)),
                ("destination_station_name", models.CharField(max_length=100)),
                ("destination_station_id", models.PositiveIntegerField()),
                ("receiver_name", models.CharField(max_length=100)),
                ("receiver_id", models.PositiveIntegerField()),
                ("receiver_okpo", models.PositiveIntegerField()),
                ("receiver_adress", models.CharField(max_length=200)),
                ("special_marks", models.CharField(max_length=200)),
                ("last_application_number", models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsAuto",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_city", models.CharField(max_length=50)),
                ("destination_city", models.CharField(max_length=50)),
                ("cost_per_tonn_auto", models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name="LogisticsRailwayStations",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("departure_station_name", models.CharField(max_length=100)),
                ("departure_station_id", models.PositiveIntegerField()),
                ("departure_station_branch", models.CharField(max_length=100)),
                ("destination_station_name", models.CharField(max_length=100)),
                ("destination_station_id", models.PositiveIntegerField()),
                ("destination_station_branch", models.CharField(max_length=100)),
                ("cost_per_tonn_rw", models.PositiveIntegerField()),
            ],
        ),
        migrations.RemoveField(
            model_name="factory",
            name="factory_full_name",
        ),
        migrations.RemoveField(
            model_name="factory",
            name="factory_short_name",
        ),
        migrations.AddField(
            model_name="factory",
            name="factory_name",
            field=models.CharField(
                choices=[
                    ("ККХП", 'АО "Курский Комбинат Хлебопродуктов'),
                    ("КХПС", 'АО "Комбинат Хлебопродуктов Старооскольский'),
                    ("ГКХП", 'АО "Городищенский Комбинат Хлебопродуктов'),
                ],
                default="ККХП",
                max_length=4,
            ),
        ),
        migrations.AlterField(
            model_name="factory",
            name="factory_adress",
            field=models.CharField(max_length=150),
        ),
    ]
