name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Lint
        run: ruff check .
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Start docker-compose database
        run: docker-compose -f docker-compose.dev.yml up -d db
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Install Python and testing
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
        run: python3 -m pytest .
      - name: Stop containers
        run: docker-compose down
