name: Check

on: push

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Lint
        run: ruff check .

  test:

    runs-on: ubuntu-latest
    container: python:3.12.2-slim
    services:
      postgres:
        image: postgres
        env:
          POSTGRES_USER: admin
          POSTGRES_PASSWORD: Melnichanka123
          POSTGRES_DB: meln_db
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Run migrations
        env:
          DATABASE_NAME: "meln_db"
          DATABASE_USER: "admin"
          DATABASE_PASSWORD: "Melnichanka123"
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432

        run: python3 manage.py migrate
      - name: Tests
        env:
          DATABASE_NAME: "meln_db"
          DATABASE_USER: "admin"
          DATABASE_PASSWORD: "Melnichanka123"
          DATABASE_HOST: postgres
          DATABASE_PORT: 5432

        run: pytest .

  types:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install requirements
        run: pip install -r requirements.txt
      - name: Check types
        run: mypy . --explicit-package-bases
